import { JobAnnouncement, Course, Category, CourseProposal, Enrollment, TrainerApplication } from './types';

export const mockJobAnnouncements: JobAnnouncement[] = [
  {
    id: '1',
    title: 'Senior Data Scientist',
    company: 'TechCorp International',
    location: 'Berlin, Germany',
    salary: '€75,000 - €95,000',
    type: 'job',
    category: 'IT',
    description: 'We are seeking an experienced Data Scientist to join our AI research team. You will work on cutting-edge machine learning projects and collaborate with cross-functional teams to deliver innovative solutions.',
    requirements: [
      'PhD or Master\'s in Computer Science, Statistics, or related field',
      '5+ years of experience in machine learning',
      'Proficiency in Python, TensorFlow, and PyTorch',
      'Strong communication skills in English'
    ],
    applicationDeadline: 'March 15, 2026',
    posted: '2 days ago',
    verified: true,
    postStatus: 'approved',
    postedByRole: 'admin',
    postedByName: 'Admin',
    postedByEmail: 'admin@platform.com',
  },
  {
    id: '2',
    title: 'PhD Position in Renewable Energy',
    company: 'ETH Zurich',
    location: 'Zurich, Switzerland',
    salary: 'CHF 50,000/year',
    type: 'doctoral',
    category: 'Engineering',
    description: 'Full-funded PhD position in renewable energy systems. The research will focus on next-generation solar cell technologies and energy storage solutions.',
    requirements: [
      'Master\'s degree in Engineering or Physics',
      'Strong background in materials science',
      'Publication record preferred',
      'Fluent in English'
    ],
    applicationDeadline: 'April 1, 2026',
    posted: '5 days ago',
    verified: true,
    postStatus: 'approved',
    postedByRole: 'admin',
    postedByName: 'Admin',
    postedByEmail: 'admin@platform.com',
  },
  {
    id: '3',
    title: 'Manufacturing Engineer',
    company: 'AutoParts GmbH',
    location: 'Stuttgart, Germany',
    salary: '€55,000 - €70,000',
    type: 'job',
    category: 'Factory',
    description: 'Join our production team to optimize manufacturing processes and implement lean methodologies in automotive component production.',
    requirements: [
      'Bachelor\'s in Mechanical or Industrial Engineering',
      '3+ years in manufacturing',
      'Experience with Six Sigma',
      'German language skills preferred'
    ],
    applicationDeadline: 'March 30, 2026',
    posted: '1 week ago',
    verified: true,
    postStatus: 'approved',
    postedByRole: 'admin',
    postedByName: 'Admin',
    postedByEmail: 'admin@platform.com',
  },
  {
    id: '4',
    title: 'Clinical Research Coordinator',
    company: 'Health Research Institute',
    location: 'London, UK',
    salary: '£40,000 - £50,000',
    type: 'job',
    category: 'Healthcare',
    description: 'Coordinate clinical trials and manage patient recruitment for cardiovascular research studies.',
    requirements: [
      'Degree in Life Sciences or Nursing',
      '2+ years clinical research experience',
      'GCP certification',
      'Excellent organizational skills'
    ],
    applicationDeadline: 'March 20, 2026',
    posted: '3 days ago',
    verified: true,
    postStatus: 'approved',
    postedByRole: 'admin',
    postedByName: 'Admin',
    postedByEmail: 'admin@platform.com',
  },
  {
    id: '5',
    title: 'Government Policy Analyst',
    company: 'Ministry of Economic Affairs',
    location: 'Brussels, Belgium',
    salary: '€60,000 - €75,000',
    type: 'job',
    category: 'Government',
    description: 'Analyze economic policies and provide strategic recommendations for EU trade regulations.',
    requirements: [
      'Master\'s in Economics or Public Policy',
      'Strong analytical and writing skills',
      'Fluency in English and French',
      'EU citizenship required'
    ],
    applicationDeadline: 'April 10, 2026',
    posted: '1 day ago',
    verified: true,
    postStatus: 'approved',
    postedByRole: 'admin',
    postedByName: 'Admin',
    postedByEmail: 'admin@platform.com',
  },
];

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Advanced Machine Learning for Professionals',
    instructor: 'Dr. Sarah Mitchell',
    instructorBio: 'PhD in AI from MIT, 15+ years in machine learning research. Former Google AI researcher.',
    price: 299,
    enrolled: 16,
    minEnrollment: 10,
    description: 'Master advanced ML techniques including deep learning, neural networks, and reinforcement learning. Hands-on projects with real-world datasets.',
    duration: '8 weeks',
    category: 'IT',
    verified: true,
    relatedJobId: '1',
    status: 'active',
  },
  {
    id: '2',
    title: 'Leadership in Healthcare Management',
    instructor: 'Prof. James Wilson',
    instructorBio: 'Harvard Medical School professor with 20 years of healthcare leadership experience.',
    price: 399,
    enrolled: 8,
    minEnrollment: 8,
    description: 'Develop essential leadership skills for healthcare professionals. Learn strategic management, team building, and healthcare policy.',
    duration: '6 weeks',
    category: 'Healthcare',
    verified: true,
    relatedJobId: '4',
    status: 'active',
  },
  {
    id: '3',
    title: 'Modern Manufacturing Systems',
    instructor: 'Eng. Maria Rodriguez',
    instructorBio: 'Industrial Engineering expert with 18 years in automotive manufacturing.',
    price: 249,
    enrolled: 12,
    minEnrollment: 10,
    description: 'Learn lean manufacturing, Industry 4.0 technologies, and quality management systems.',
    duration: '5 weeks',
    category: 'Factory',
    verified: true,
    relatedJobId: '3',
    status: 'active',
  },
  {
    id: '4',
    title: 'Research Methodology & Academic Writing',
    instructor: 'Dr. Ahmed Hassan',
    instructorBio: 'Published researcher with 100+ papers, specializing in academic writing and methodology.',
    price: 199,
    enrolled: 18,
    minEnrollment: 15,
    description: 'Master research design, data analysis, and academic writing for journal publications.',
    duration: '4 weeks',
    category: 'Academic',
    verified: true,
    relatedJobId: '2',
    status: 'active',
  },
];

export const mockCourseProposals: CourseProposal[] = [
  {
    id: 'prop1',
    courseTitle: 'Data Science Bootcamp for Career Switchers',
    courseDescription: 'Complete hands-on bootcamp covering Python, SQL, Machine Learning, and Data Visualization. Perfect for professionals looking to transition into data science roles.',
    skillsCovered: ['Python', 'SQL', 'Machine Learning', 'Data Visualization', 'Statistics'],
    duration: '12 weeks',
    deliveryMode: 'online',
    basePrice: 350,
    platformCommission: 50,
    finalPrice: 400,
    minStudents: 10,
    maxStudents: 30,
    startDate: '2026-04-01',
    instructorBio: 'Data Scientist with 8 years of experience at top tech companies. Mentored 100+ students.',
    relatedJobId: '1',
    relatedJobTitle: 'Senior Data Scientist',
    trainerId: 'trainer1',
    trainerName: 'Dr. Sarah Mitchell',
    trainerEmail: 'sarah@example.com',
    status: 'pending',
    createdAt: '2026-02-20',
  },
  {
    id: 'prop2',
    courseTitle: 'EU Policy Analysis & Research Methods',
    courseDescription: 'Comprehensive course on European Union policy-making, economic analysis, and research methodologies for government professionals.',
    skillsCovered: ['Policy Analysis', 'Economic Research', 'Report Writing', 'Stakeholder Management'],
    duration: '6 weeks',
    deliveryMode: 'hybrid',
    basePrice: 280,
    platformCommission: 70,
    finalPrice: 350,
    minStudents: 8,
    maxStudents: 20,
    startDate: '2026-03-15',
    instructorBio: 'Former EU policy advisor with 12 years of experience in economic affairs.',
    relatedJobId: '5',
    relatedJobTitle: 'Government Policy Analyst',
    trainerId: 'trainer2',
    trainerName: 'Prof. Elena Dubois',
    trainerEmail: 'sarah@example.com',
    status: 'approved',
    createdAt: '2026-02-15',
  },
  {
    id: 'prop3',
    courseTitle: 'Clinical Trial Management Fundamentals',
    courseDescription: 'Essential skills for coordinating clinical research, from protocol development to data management and regulatory compliance.',
    skillsCovered: ['GCP Guidelines', 'Patient Recruitment', 'Data Management', 'Regulatory Compliance'],
    duration: '8 weeks',
    deliveryMode: 'online',
    basePrice: 220,
    platformCommission: 55,
    finalPrice: 275,
    minStudents: 12,
    maxStudents: 25,
    startDate: '2026-04-10',
    instructorBio: 'Clinical Research Professional with 10 years managing cardiovascular trials.',
    relatedJobId: '4',
    relatedJobTitle: 'Clinical Research Coordinator',
    trainerId: 'trainer3',
    trainerName: 'Dr. Michael Chen',
    trainerEmail: 'sarah@example.com',
    status: 'rejected',
    createdAt: '2026-02-10',
    adminFeedback: 'Course content needs more detail on regulatory frameworks. Please revise and resubmit with specific examples.',
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: 'enroll1',
    courseId: '1',
    courseTitle: 'Advanced Machine Learning for Professionals',
    studentName: 'John Doe',
    studentEmail: 'john.doe@example.com',
    enrolledDate: '2026-01-15',
    status: 'enrolled',
    progress: 65,
  },
  {
    id: 'enroll2',
    courseId: '1',
    courseTitle: 'Advanced Machine Learning for Professionals',
    studentName: 'Jane Smith',
    studentEmail: 'jane.smith@example.com',
    enrolledDate: '2026-01-16',
    status: 'enrolled',
    progress: 72,
  },
  {
    id: 'enroll3',
    courseId: '1',
    courseTitle: 'Advanced Machine Learning for Professionals',
    studentName: 'Ahmed Ali',
    studentEmail: 'ahmed.ali@example.com',
    enrolledDate: '2026-01-18',
    status: 'completed',
    progress: 100,
  },
  {
    id: 'enroll4',
    courseId: '3',
    courseTitle: 'Modern Manufacturing Systems',
    studentName: 'Maria Garcia',
    studentEmail: 'maria.garcia@example.com',
    enrolledDate: '2026-01-20',
    status: 'enrolled',
    progress: 45,
  },
  {
    id: 'enroll5',
    courseId: '3',
    courseTitle: 'Modern Manufacturing Systems',
    studentName: 'Thomas Mueller',
    studentEmail: 'thomas.mueller@example.com',
    enrolledDate: '2026-01-22',
    status: 'enrolled',
    progress: 50,
  },
];

export const mockTrainerApplications: TrainerApplication[] = [
  {
    id: 'app1',
    name: 'Dr. Sarah Mitchell',
    email: 'sarah@example.com',
    phoneNumber: '+1 555 0101',
    profession: 'Data Scientist & Machine Learning Expert',
    bio: 'PhD in Artificial Intelligence from MIT with over 15 years of experience in machine learning research and development. Former senior researcher at Google AI, published over 50 papers in top-tier conferences. Passionate about teaching and have mentored over 100 students in data science and ML. Specializing in deep learning, neural networks, and practical applications of AI in industry.',
    cvFile: 'mock-cv-sarah.pdf',
    cvFileName: 'Sarah_Mitchell_CV.pdf',
    appliedDate: '2026-02-15',
    status: 'approved',
  },
  {
    id: 'app2',
    name: 'Prof. Michael Chen',
    email: 'michael.chen@example.com',
    phoneNumber: '+44 20 7946 0958',
    profession: 'Healthcare Management Consultant',
    bio: 'Medical doctor with MBA from Harvard Business School. Over 20 years of experience in healthcare administration and clinical research coordination. Certified in Good Clinical Practice (GCP) and have led multiple international clinical trials for cardiovascular research. Expert in patient recruitment strategies, regulatory compliance, and data management protocols.',
    cvFile: 'mock-cv-michael.pdf',
    cvFileName: 'Michael_Chen_CV.pdf',
    appliedDate: '2026-02-18',
    status: 'pending',
  },
  {
    id: 'app3',
    name: 'Elena Rodriguez',
    email: 'elena.rodriguez@example.com',
    phoneNumber: '+49 30 12345678',
    profession: 'Manufacturing Engineer',
    bio: 'Industrial Engineer with 12 years in automotive manufacturing. Experience with lean methodologies and Six Sigma implementation.',
    cvFile: 'mock-cv-elena.pdf',
    cvFileName: 'Elena_Rodriguez_CV.pdf',
    appliedDate: '2026-02-20',
    status: 'rejected',
    adminFeedback: 'Bio is too brief. Please provide more details about your teaching experience and specific achievements in manufacturing optimization.',
  },
];

export const categories: Category[] = [
  { id: '1', name: 'Doctoral Positions', icon: 'GraduationCap' },
  { id: '2', name: 'Factory Jobs', icon: 'Factory' },
  { id: '3', name: 'Engineering', icon: 'Cog' },
  { id: '4', name: 'Healthcare', icon: 'HeartPulse' },
  { id: '5', name: 'IT', icon: 'Code' },
  { id: '6', name: 'Government', icon: 'Building2' },
];