import { supabase } from './supabase';
import {
  JobAnnouncement,
  Course,
  CourseProposal,
  Enrollment,
  TrainerApplication,
  User
} from '../app/types';
import { Capacitor } from '@capacitor/core';
import { Browser } from '@capacitor/browser';

// Helper to convert snake_case DB columns to camelCase matching our types.ts
export function toCamelCase(obj: any): any {
  if (Array.isArray(obj)) return obj.map(toCamelCase);
  if (obj !== null && typeof obj === 'object') {
    return Object.fromEntries(
      Object.entries(obj).map(([key, value]) => [
        key.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase()),
        toCamelCase(value)
      ])
    );
  }
  return obj;
}

// Helper to convert frontend camelCase to Postgres snake_case before saving
export function toSnakeCase(obj: any): any {
  if (Array.isArray(obj)) return obj.map(toSnakeCase);
  if (obj !== null && typeof obj === 'object') {
    return Object.fromEntries(
      Object.entries(obj).map(([key, value]) => [
        key.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`),
        toSnakeCase(value)
      ])
    );
  }
  return obj;
}

// ----------------------------------------------------
// AUTH ACTIONS
// ----------------------------------------------------

export async function signUpUser(email: string, password: string, name: string, role: string, profession: string = '', country: string = '') {
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
    options: {
      data: { full_name: name, role: role, profession: profession, country: country }
    }
  });
  if (error) throw error;
  return data;
}

export async function signInUser(email: string, password: string) {
  const { data, error } = await supabase.auth.signInWithPassword({ email, password });
  if (error) throw error;
  return data;
}

export async function signInWithGoogle() {
  const isNative = Capacitor.isNativePlatform();
  const redirectTo = isNative ? 'com.skillbridge.app://login-callback' : window.location.origin;

  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo: redirectTo,
      skipBrowserRedirect: isNative
    }
  });
  if (error) throw error;

  if (isNative && data?.url) {
    await Browser.open({ url: data.url });
  }
  return data;
}

export async function signOutUser() {
  const { error } = await supabase.auth.signOut();
  if (error) throw error;
}

export async function verifyEmailOtp(email: string, token: string) {
  const { data, error } = await supabase.auth.verifyOtp({
    email,
    token,
    type: 'signup'
  });
  if (error) throw error;
  return data;
}

export async function resendOtp(email: string) {
  const { data, error } = await supabase.auth.resend({
    type: 'signup',
    email,
  });
  if (error) throw error;
  return data;
}

export async function resetPassword(email: string) {
  const { data, error } = await supabase.auth.resetPasswordForEmail(email, {
    redirectTo: window.location.origin,
  });
  if (error) throw error;
  return data;
}

export async function getCurrentUser() {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;

  let { data: profile, error } = await supabase
    .from('users')
    .select('*')
    .eq('id', user.id)
    .single();

  if (error && error.code === 'PGRST116') {
    // No profile found, create default one
    const newProfile = {
      id: user.id,
      name: user.user_metadata?.full_name || user.email?.split('@')[0] || 'User',
      email: user.email,
      role: 'user',
      trainer_status: 'pending',
      profession: 'Professional',
      created_at: new Date().toISOString()
    };
    const { data: created, error: insertError } = await supabase
      .from('users')
      .insert(newProfile)
      .select()
      .single();

    if (insertError) {
      console.error("Error creating user profile:", insertError);
      return { authUser: user, profile: null };
    }
    profile = created;
  } else if (error) {
    console.error("Error fetching user profile:", error);
    return { authUser: user, profile: null };
  }

  return { authUser: user, profile: toCamelCase(profile) as User };
}

// ----------------------------------------------------
// DB ACTIONS
// ----------------------------------------------------

export async function fetchJobs() {
  const { data, error } = await supabase.from('job_announcements').select('*').order('created_at', { ascending: false });
  if (error) throw error;
  return toCamelCase(data) as JobAnnouncement[];
}

export async function createJob(job: Partial<JobAnnouncement>) {
  // Remove id if it's generated by frontend to let DB handle it. Or keep it if we format it as UUID. 
  // Since frontend uses string IDs right now, it's easiest to let DB enforce UUIDs and omit the frontend id.
  const { id, ...jobWithoutId } = job;
  const payload = toSnakeCase(jobWithoutId);

  const { data, error } = await supabase.from('job_announcements').insert(payload).select().single();
  if (error) throw error;
  return toCamelCase(data) as JobAnnouncement;
}

export async function updateJobStatus(id: string, status: string, feedback?: string) {
  const { data, error } = await supabase
    .from('job_announcements')
    .update({ post_status: status, admin_feedback: feedback })
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return toCamelCase(data) as JobAnnouncement;
}

export async function fetchCourses() {
  const { data, error } = await supabase.from('courses').select('*').order('created_at', { ascending: false });
  if (error) throw error;
  return toCamelCase(data) as Course[];
}

export async function createCourse(course: Partial<Course>) {
  const { id, ...courseWithoutId } = course;
  const payload = toSnakeCase(courseWithoutId);
  const { data, error } = await supabase.from('courses').insert(payload).select().single();
  if (error) throw error;
  return toCamelCase(data) as Course;
}

export async function fetchProposals() {
  const { data, error } = await supabase.from('course_proposals').select('*').order('created_at', { ascending: false });
  if (error) throw error;
  return toCamelCase(data) as CourseProposal[];
}

export async function saveProposal(proposal: Partial<CourseProposal>) {
  const { id, ...withoutId } = proposal;
  // If id starts with 'prop' it's a frontend generated mock ID, we need to omitt it for Supabase to gen UUID
  const isExisting = id && !id.startsWith('prop');

  const payload = toSnakeCase(isExisting ? proposal : withoutId);

  const { data: { user } } = await supabase.auth.getUser();
  if (user && !isExisting) {
    payload.trainer_id = user.id;
  }

  if (isExisting) {
    const { data, error } = await supabase.from('course_proposals').update(payload).eq('id', id).select().single();
    if (error) throw error;
    return toCamelCase(data) as CourseProposal;
  } else {
    const { data, error } = await supabase.from('course_proposals').insert(payload).select().single();
    if (error) throw error;
    return toCamelCase(data) as CourseProposal;
  }
}

export async function updateProposalStatus(id: string, status: string, feedback?: string) {
  const { data, error } = await supabase
    .from('course_proposals')
    .update({ status, admin_feedback: feedback })
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return toCamelCase(data) as CourseProposal;
}

export async function fetchTrainerApplications() {
  const { data, error } = await supabase.from('trainer_applications').select('*').order('applied_date', { ascending: false });
  if (error) throw error;
  return toCamelCase(data) as TrainerApplication[];
}

export async function submitTrainerApplication(application: Partial<TrainerApplication>) {
  const { id, ...withoutId } = application;
  const payload = toSnakeCase(withoutId);

  const { data: { user } } = await supabase.auth.getUser();
  if (user) {
    payload.user_id = user.id;
  }

  const { data, error } = await supabase.from('trainer_applications').insert(payload).select().single();
  if (error) throw error;
  return toCamelCase(data) as TrainerApplication;
}

export async function updateApplicationStatus(id: string, status: string, feedback?: string) {
  const { data, error } = await supabase
    .from('trainer_applications')
    .update({ status, admin_feedback: feedback })
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return toCamelCase(data) as TrainerApplication;
}

export async function fetchEnrollments() {
  const { data, error } = await supabase.from('enrollments').select('*').order('enrolled_date', { ascending: false });
  if (error) throw error;
  return toCamelCase(data) as Enrollment[];
}

export async function updateUserProfile(userId: string, updates: Partial<User>) {
  const payload = toSnakeCase(updates);
  const { data, error } = await supabase
    .from('users')
    .update(payload)
    .eq('id', userId)
    .select()
    .single();

  if (error) throw error;
  return toCamelCase(data) as User;
}

export async function uploadProfileImage(userId: string, file: File) {
  const fileExt = file.name.split('.').pop();
  const fileName = `${userId}-${Math.random()}.${fileExt}`;
  const filePath = `avatars/${fileName}`;

  const { error: uploadError } = await supabase.storage
    .from('avatars')
    .upload(filePath, file);

  if (uploadError) throw uploadError;

  const { data: { publicUrl } } = supabase.storage
    .from('avatars')
    .getPublicUrl(filePath);

  return publicUrl;
}

export async function changePassword(newPassword: string) {
  const { data, error } = await supabase.auth.updateUser({
    password: newPassword,
  });
  if (error) throw error;
  return data;
}

// ----------------------------------------------------
// JOB APPLICATIONS
// ----------------------------------------------------

export async function applyToJob(jobId: string, userEmail: string, userName: string) {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  const { data, error } = await supabase
    .from('job_applications')
    .insert({
      user_id: user.id,
      user_email: userEmail,
      user_name: userName,
      job_id: jobId,
    })
    .select()
    .single();
  if (error) throw error;
  return toCamelCase(data);
}

export async function withdrawApplication(jobId: string) {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  const { error } = await supabase
    .from('job_applications')
    .delete()
    .eq('user_id', user.id)
    .eq('job_id', jobId);
  if (error) throw error;
}

export async function fetchUserApplications() {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return [];

  const { data, error } = await supabase
    .from('job_applications')
    .select('*')
    .eq('user_id', user.id)
    .order('applied_at', { ascending: false });
  if (error) throw error;
  return toCamelCase(data) as { id: string; jobId: string; appliedAt: string }[];
}

// ----------------------------------------------------
// ADMIN JOB MANAGEMENT
// ----------------------------------------------------

export async function deleteJob(jobId: string) {
  const { error } = await supabase
    .from('job_announcements')
    .delete()
    .eq('id', jobId);
  if (error) throw error;
}

export async function updateJob(jobId: string, updates: Partial<JobAnnouncement>) {
  const { id, ...rest } = updates;
  const payload = toSnakeCase(rest);
  const { data, error } = await supabase
    .from('job_announcements')
    .update(payload)
    .eq('id', jobId)
    .select()
    .single();
  if (error) throw error;
  return toCamelCase(data) as JobAnnouncement;
}

// ----------------------------------------------------
// DEADLINE REMINDERS
// ----------------------------------------------------

export async function triggerDeadlineReminders() {
  const { data, error } = await supabase.functions.invoke('deadline-reminders');
  if (error) throw error;
  return data as {
    message: string;
    emailsSent: number;
    debug?: { jobsFound: number; applicationsFound: number; emailFailures: string[] }
  };
}

// ----------------------------------------------------
// COURSE ENROLLMENT (JOIN / LEAVE)
// ----------------------------------------------------

export async function joinCourse(
  courseId: string,
  courseTitle: string,
  studentName: string,
  studentEmail: string
) {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  // Check not already enrolled
  const { data: existing } = await supabase
    .from('enrollments')
    .select('id')
    .eq('course_id', courseId)
    .eq('student_email', studentEmail)
    .maybeSingle();

  if (existing) throw new Error('Already enrolled in this course');

  const payload = {
    course_id: courseId,
    student_name: studentName,
    student_email: studentEmail,
    enrolled_date: new Date().toISOString(),
    status: 'enrolled',
    progress: 0,
  };

  const { data, error } = await supabase
    .from('enrollments')
    .insert(payload)
    .select()
    .single();
  if (error) throw error;

  // Increment enrolled count on the course (best-effort — ignore if RPC not set up)
  supabase.rpc('increment_course_enrollment', { course_id_param: courseId }).catch(() => {});

  // Send enrollment confirmation email (best-effort)
  supabase.functions.invoke('send-notification', {
    body: {
      type: 'enrollment_confirmation',
      payload: { userEmail: studentEmail, userName: studentName, courseTitle },
    },
  }).catch(() => {});

  return toCamelCase(data) as Enrollment;
}

export async function leaveCourse(enrollmentId: string, courseId: string) {
  const { data: enrollment, error: fetchError } = await supabase
    .from('enrollments')
    .select('enrolled_date')
    .eq('id', enrollmentId)
    .single();

  if (fetchError || !enrollment) throw new Error('Enrollment not found');

  const enrolledAt = new Date(enrollment.enrolled_date);
  const hoursSinceJoin = (Date.now() - enrolledAt.getTime()) / (1000 * 60 * 60);

  if (hoursSinceJoin > 24) {
    throw new Error('You can only leave within 24 hours of joining');
  }

  const { error } = await supabase
    .from('enrollments')
    .delete()
    .eq('id', enrollmentId);
  if (error) throw error;

  // Decrement enrolled count on the course (best-effort — ignore if RPC not set up)
  supabase.rpc('decrement_course_enrollment', { course_id_param: courseId }).catch(() => {});
}

// ----------------------------------------------------
// COURSE CHAT
// ----------------------------------------------------

export interface CourseMessage {
  id: string;
  courseId: string;
  senderEmail: string;
  senderName: string;
  isInstructor: boolean;
  message: string;
  createdAt: string;
}

export async function fetchCourseMessages(courseId: string): Promise<CourseMessage[]> {
  const { data, error } = await supabase
    .from('course_messages')
    .select('*')
    .eq('course_id', courseId)
    .order('created_at', { ascending: true });
  if (error) throw error;
  return toCamelCase(data) as CourseMessage[];
}

export async function sendCourseMessage(
  courseId: string,
  senderEmail: string,
  senderName: string,
  message: string,
  isInstructor: boolean = false
) {
  const { data, error } = await supabase
    .from('course_messages')
    .insert({
      course_id: courseId,
      sender_email: senderEmail,
      sender_name: senderName,
      is_instructor: isInstructor,
      message,
    })
    .select()
    .single();
  if (error) throw error;
  return toCamelCase(data) as CourseMessage;
}

// ----------------------------------------------------
// NOTIFICATION PREFERENCES
// ----------------------------------------------------

export interface NotificationPrefs {
  newCourses: boolean;
  jobUpdates: boolean;
  enrollments: boolean;
  promotional: boolean;
}

/** Save notification preferences to the users table in Supabase */
export async function saveNotificationPrefs(prefs: NotificationPrefs) {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return;

  // Best-effort — columns may not exist yet; errors are silently ignored
  await supabase
    .from('users')
    .update({
      notify_new_courses: prefs.newCourses,
      notify_job_updates: prefs.jobUpdates,
      notify_enrollments: prefs.enrollments,
      notify_promotional: prefs.promotional,
    })
    .eq('id', user.id)
    .then(({ error }) => {
      if (error) console.warn('Could not save notification prefs to DB:', error.message);
    });
}

/** Trigger a notification email for all opted-in users (called after admin approves course/job) */
export async function triggerNotification(
  type: 'new_course' | 'new_job',
  payload: Record<string, unknown>
) {
  await supabase.functions.invoke('send-notification', { body: { type, payload } });
}
