import { supabase } from './supabase';
import { 
  JobAnnouncement, 
  Course, 
  CourseProposal, 
  Enrollment, 
  TrainerApplication, 
  User 
} from '../app/types';

// Helper to convert snake_case DB columns to camelCase matching our types.ts
export function toCamelCase(obj: any): any {
  if (Array.isArray(obj)) return obj.map(toCamelCase);
  if (obj !== null && typeof obj === 'object') {
    return Object.fromEntries(
      Object.entries(obj).map(([key, value]) => [
        key.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase()),
        toCamelCase(value)
      ])
    );
  }
  return obj;
}

// Helper to convert frontend camelCase to Postgres snake_case before saving
export function toSnakeCase(obj: any): any {
  if (Array.isArray(obj)) return obj.map(toSnakeCase);
  if (obj !== null && typeof obj === 'object') {
    return Object.fromEntries(
      Object.entries(obj).map(([key, value]) => [
        key.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`),
        toSnakeCase(value)
      ])
    );
  }
  return obj;
}

// ----------------------------------------------------
// AUTH ACTIONS
// ----------------------------------------------------

export async function signUpUser(email: string, password: string, name: string, role: string, profession: string = '', country: string = '') {
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
    options: {
      data: { full_name: name, role: role, profession: profession, country: country }
    }
  });
  if (error) throw error;
  return data;
}

export async function signInUser(email: string, password: string) {
  const { data, error } = await supabase.auth.signInWithPassword({ email, password });
  if (error) throw error;
  return data;
}

export async function signInWithGoogle() {
  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo: window.location.origin
    }
  });
  if (error) throw error;
  return data;
}

export async function signOutUser() {
  const { error } = await supabase.auth.signOut();
  if (error) throw error;
}

export async function verifyEmailOtp(email: string, token: string) {
  const { data, error } = await supabase.auth.verifyOtp({
    email,
    token,
    type: 'signup'
  });
  if (error) throw error;
  return data;
}

export async function resendOtp(email: string) {
  const { data, error } = await supabase.auth.resend({
    type: 'signup',
    email,
  });
  if (error) throw error;
  return data;
}

export async function resetPassword(email: string) {
  const { data, error } = await supabase.auth.resetPasswordForEmail(email, {
    redirectTo: window.location.origin,
  });
  if (error) throw error;
  return data;
}

export async function getCurrentUser() {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;

  const { data: profile, error } = await supabase
    .from('users')
    .select('*')
    .eq('id', user.id)
    .single();

  if (error) {
    console.error("Error fetching user profile:", error);
    return { authUser: user, profile: null };
  }
  
  return { authUser: user, profile: toCamelCase(profile) as User };
}

// ----------------------------------------------------
// DB ACTIONS
// ----------------------------------------------------

export async function fetchJobs() {
  const { data, error } = await supabase.from('job_announcements').select('*').order('created_at', { ascending: false });
  if (error) throw error;
  return toCamelCase(data) as JobAnnouncement[];
}

export async function createJob(job: Partial<JobAnnouncement>) {
  // Remove id if it's generated by frontend to let DB handle it. Or keep it if we format it as UUID. 
  // Since frontend uses string IDs right now, it's easiest to let DB enforce UUIDs and omit the frontend id.
  const { id, ...jobWithoutId } = job; 
  const payload = toSnakeCase(jobWithoutId);
  
  const { data, error } = await supabase.from('job_announcements').insert(payload).select().single();
  if (error) throw error;
  return toCamelCase(data) as JobAnnouncement;
}

export async function updateJobStatus(id: string, status: string, feedback?: string) {
  const { data, error } = await supabase
    .from('job_announcements')
    .update({ post_status: status, admin_feedback: feedback })
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return toCamelCase(data) as JobAnnouncement;
}

export async function fetchCourses() {
  const { data, error } = await supabase.from('courses').select('*').order('created_at', { ascending: false });
  if (error) throw error;
  return toCamelCase(data) as Course[];
}

export async function createCourse(course: Partial<Course>) {
  const { id, ...courseWithoutId } = course;
  const payload = toSnakeCase(courseWithoutId);
  const { data, error } = await supabase.from('courses').insert(payload).select().single();
  if (error) throw error;
  return toCamelCase(data) as Course;
}

export async function fetchProposals() {
  const { data, error } = await supabase.from('course_proposals').select('*').order('created_at', { ascending: false });
  if (error) throw error;
  return toCamelCase(data) as CourseProposal[];
}

export async function saveProposal(proposal: Partial<CourseProposal>) {
  const { id, ...withoutId } = proposal;
  // If id starts with 'prop' it's a frontend generated mock ID, we need to omitt it for Supabase to gen UUID
  const isExisting = id && !id.startsWith('prop');
  
  const payload = toSnakeCase(isExisting ? proposal : withoutId);
  
  const { data: { user } } = await supabase.auth.getUser();
  if (user && !isExisting) {
    payload.trainer_id = user.id;
  }
  
  if (isExisting) {
    const { data, error } = await supabase.from('course_proposals').update(payload).eq('id', id).select().single();
    if (error) throw error;
    return toCamelCase(data) as CourseProposal;
  } else {
    const { data, error } = await supabase.from('course_proposals').insert(payload).select().single();
    if (error) throw error;
    return toCamelCase(data) as CourseProposal;
  }
}

export async function updateProposalStatus(id: string, status: string, feedback?: string) {
  const { data, error } = await supabase
    .from('course_proposals')
    .update({ status, admin_feedback: feedback })
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return toCamelCase(data) as CourseProposal;
}

export async function fetchTrainerApplications() {
  const { data, error } = await supabase.from('trainer_applications').select('*').order('applied_date', { ascending: false });
  if (error) throw error;
  return toCamelCase(data) as TrainerApplication[];
}

export async function submitTrainerApplication(application: Partial<TrainerApplication>) {
  const { id, ...withoutId } = application;
  const payload = toSnakeCase(withoutId);
  
  const { data: { user } } = await supabase.auth.getUser();
  if (user) {
    payload.user_id = user.id;
  }
  
  const { data, error } = await supabase.from('trainer_applications').insert(payload).select().single();
  if (error) throw error;
  return toCamelCase(data) as TrainerApplication;
}

export async function updateApplicationStatus(id: string, status: string, feedback?: string) {
  const { data, error } = await supabase
    .from('trainer_applications')
    .update({ status, admin_feedback: feedback })
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return toCamelCase(data) as TrainerApplication;
}

export async function fetchEnrollments() {
  const { data, error } = await supabase.from('enrollments').select('*').order('enrolled_date', { ascending: false });
  if (error) throw error;
  return toCamelCase(data) as Enrollment[];
}

export async function updateUserProfile(userId: string, updates: Partial<User>) {
  const payload = toSnakeCase(updates);
  const { data, error } = await supabase
    .from('users')
    .update(payload)
    .eq('id', userId)
    .select()
    .single();
  
  if (error) throw error;
  return toCamelCase(data) as User;
}

export async function uploadProfileImage(userId: string, file: File) {
  const fileExt = file.name.split('.').pop();
  const fileName = `${userId}-${Math.random()}.${fileExt}`;
  const filePath = `avatars/${fileName}`;

  const { error: uploadError } = await supabase.storage
    .from('avatars')
    .upload(filePath, file);

  if (uploadError) throw uploadError;

  const { data: { publicUrl } } = supabase.storage
    .from('avatars')
    .getPublicUrl(filePath);

  return publicUrl;
}

export async function changePassword(newPassword: string) {
  const { data, error } = await supabase.auth.updateUser({
    password: newPassword,
  });
  if (error) throw error;
  return data;
}
